### ISSUE TITLE
Sync GitHub release version number with PyPI release version number

### ISSUE THREAD

**Issue by impredicative** [html-extract/hext#23]
Congratulations on v1.0.0!

**For future releases**, is it possible for the GitHub release version number to match the one in PyPI? Currently the two seem very much out of sync, and this makes it confusing. They're v1.0.0 and 0.3.0 respectively.

This doesn't mean that the two always need to be released together in sequence. A `patch` increment doesn't strictly need to match. Only the `major` and `minor` increments ideally need to match.

Thanks.

**Comment by thomastrapp** [comment]
True.

There will be another pypi release soon (The "max_searches" parameter is not implemented for `Rule::extract` yet, in the language bindings). I'll use 1.0.0 then.

The npm version is even more out of whack - The package name "hext" had a prior owner on npm and some versions were already used up.

> A patch increment doesn't strictly need to match. Only the major and minor increments ideally need to match.

Yes, that's a good rule of thumb.

A single version for pypi, htmlext and libhext would probably be best. Maybe I'll add better tooling, that automatically publishes releases when a new git tag is created, or something like that.

**Comment by thomastrapp** [comment]
The versions are now in sync, and it is enforced by CI.

The PyPI and NPM releases are not automatically published. But, I have reduced the amount of work per release down to a minimum, because everything is now built directly on Github, with every commit. This way I can release often, without a headache.

Thank you for creating this issue!
